// CommonJS Modules
const express = require('express');
const mongoose = require('mongoose');
const cookieSession = require('cookie-session');
const passport = require('passport');
const keys = require('./config/keys');
require('./models/User'); // models must be loaded before passport
require('./services/passport'); // require executes ./services/passport file, w/c doesn't return anything

// connect to mongodb database/cluster
mongoose.connect(keys.mongoURI);

const app = express();

// store token generated by passport into a cookie
app.use(
  cookieSession({
    maxAge: 30 * 24 * 60 * 60 * 1000, // 30 days in milliseconds
    keys: [keys.cookieKey], // key used to encrypt cookie
  })
);

// tell passport to use cookies to handle authentication
app.use(passport.initialize());
app.use(passport.session());

// require executes ./routes/authRoutes file, w/c returns a function
// then the function is executed, where app is passed as an arg
require('./routes/authRoutes')(app);

const PORT = process.env.PORT || 5000;
app.listen(PORT, '0.0.0.0');
